var tests = [
  ['no arguments', [], '<div></div>'],
  ['with blank string', [''], '<div></div>'],
  ['with "div"', ['div'], '<div></div>'],
  ['with id', ['#test'], '<div id="test"></div>'],
  ['with class', ['.test'], '<div class="test"></div>'],
  ['with class and id', ['.class#id'], '<div id="id" class="class"></div>'],
  ['with id and class', ['#id.class'], '<div id="id" class="class"></div>'],
  ['with "span"', ['span'], '<span></span>'],
  ['with tag and id', ['p#id'], '<p id="id"></p>'],
  ['with tag and class', ['p.class'], '<p class="class"></p>'],
  ['with tag and id and class', ['p#id.class'], '<p id="id" class="class"></p>'],
  ['with tag and class and id', ['p.class#id'], '<p id="id" class="class"></p>'],
  ['with multiple classes', ['.class1.class2.class3'], '<div class="class1 class2 class3"></div>'],
  ['with multiple ids', ['#id1#id2'], '<div id="id2"></div>'],
  ['with content', ['{test content}'], '<div>test content</div>'],
  ['with tag and content', ['span{test content}'], '<span>test content</span>'],
  ['with id and content', ['#id{content string}'], '<div id="id">content string</div>'],
  ['with id and content and class', ['#id{content}.class'], '<div id="id" class="class">content</div>'],
  ['with unclosed content', ['span{my content'], null],
  ['with empty content', ['{}'], '<div></div>'],
  ['with content argument', ['span', 'my content'], '<span>my content</span>'],
  ['with an attribute', ['a#id', {href: '/link'}], '<a id="id" href="/link"></a>'],
  ['with multiple attributes', ['a#id', {title:'my link', href:'#link'}], '<a id="id" title="my link" href="#link"></a>'],
  ['with attributes and content argument', ['a#id', {title:'my link', href:'#link'}, 'content'], '<a id="id" title="my link" href="#link">content</a>'],
  ['with element as content argument', ['#id', $.build('a.link')], '<div id="id"><a class="link"></a></div>'],
  ['with multiple elements as content argument', ['ul.list', [$.build('li#n1{one}'), $.build('li#n2{two}')]], '<ul class="list"><li id="n1">one</li><li id="n2">two</li></ul>']
];